export enum Page {
  HOME = 'HOME',
  PRIVATE_OFFICE = 'PRIVATE_OFFICE',
  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  USER_TEST = 'USER_TEST',
  USER_TEST_ROUTE = 'USER_TEST_ROUTE',
  USER_TEST_COMPLETE = 'USER_TEST_COMPLETE',
  ADMIN = 'ADMIN',
  PAGES = 'PAGES',
  PAGE = 'PAGE',
  PAGE_ROUTE = 'PAGE_ROUTE',
  PARTICIPANT_INFO = 'PARTICIPANT_INFO',
  PARTICIPANT_INFO_ROUTE = 'PARTICIPANT_INFO_ROUTE',
}

export const paths = {
  [Page.LOGIN]: '/login',
  [Page.HOME]: '/',
  [Page.PRIVATE_OFFICE]: '/private-office',
  [Page.SIGN_UP]: '/sign-up',
  [Page.FORGOT_PASSWORD]: '/forgot-password',
  [Page.USER_TEST]: '/user-test',
  [Page.USER_TEST_COMPLETE]: '/user-test/complete',
  [Page.USER_TEST_ROUTE]: '/user-test/:questionNumber',
  [Page.ADMIN]: '/admin',
  [Page.PAGES]: '/pages',
  [Page.PAGE]: '/page',
  [Page.PAGE_ROUTE]: '/page/:id',
  [Page.PARTICIPANT_INFO]: '/participant-info',
  [Page.PARTICIPANT_INFO_ROUTE]: '/participant-info/:id',
}
