export const SET_STATE_ANSWERS = "SET_STATE_ANSWERS";
export const SET_STATE_IS_TIMER_FINISHED = "SET_STATE_IS_TIMER_FINISHED";
export const SET_JWT_PAIR = "SET_JWT_PAIR";
export const SET_STATE_CURRENT_ID = "SET_STATE_CURRENT_ID";
export const SET_STATE_CREATION_MODE_EDIT = "SET_STATE_CREATION_MODE_EDIT";
export const SET_STATE_CREATION_MODE_CREATE = "SET_STATE_CREATION_MODE_CREATE";
