export enum AdminsPage {
  NEWS = 'NEWS',
  NEWS_CREATE = 'NEWS_CREATE',
  NEWS_EDIT = 'NEWS_EDIT',
  MAIN = 'MAIN',
  MENU = 'MENU',
  STATISTICS = 'STATISTICS',
  PARTICIPANTS = 'PARTICIPANTS',
  ADD_PARTICIPANT = 'ADD_PARTICIPANT',
  EDIT_PARTICIPANT = 'EDIT_PARTICIPANT',
  COUNTER = 'COUNTER',
  FAQ = 'FAQ',
  TEST_QUESTUIONS = 'TEST_QUESTUIONS',
  PARTNERS = 'PARTNERS',
  ADD_PARTNER = 'ADD_PARTNER',
  EDIT_PARTNER = 'EDIT_PARTNER',
  PROJECT_PERSONS = 'PROJECT_PERSONS',
}

export const paths = {
  [AdminsPage.NEWS]: '/admin/news',
  [AdminsPage.NEWS_CREATE]: '/admin/news/create',
  [AdminsPage.NEWS_EDIT]: '/admin/news/edit',
  [AdminsPage.MAIN]: '/admin/',
  [AdminsPage.MENU]: '/admin/menu',
  [AdminsPage.STATISTICS]: '/admin/statistics',
  [AdminsPage.PARTICIPANTS]: '/admin/participants',
  [AdminsPage.ADD_PARTICIPANT]: '/admin/participants/create',
  [AdminsPage.EDIT_PARTICIPANT]: '/admin/participants/edit',
  [AdminsPage.COUNTER]: '/admin/counter',
  [AdminsPage.FAQ]: '/admin/faq',
  [AdminsPage.TEST_QUESTUIONS]: '/admin/test-questions',
  [AdminsPage.PARTNERS]: '/admin/partners',
  [AdminsPage.ADD_PARTNER]: '/admin/partners/create',
  [AdminsPage.EDIT_PARTNER]: '/admin/partners/edit',
  [AdminsPage.PROJECT_PERSONS]: '/admin/project-persons',
}