export enum AdminsPage {
  NEWS = 'NEWS',
  NEWS_CREATE = 'NEWS_CREATE',
  NEWS_EDIT = 'NEWS_EDIT',
  NEWS_EDIT_ROUTE = 'NEWS_EDIT_ROUTE',
  MAIN = 'MAIN',
  MENU = 'MENU',
  MENU_ROUTE = 'MENU_DETAIL_ROUTE',
  STATISTICS = 'STATISTICS',
  PARTICIPANTS = 'PARTICIPANTS',
  ADD_PARTICIPANT = 'ADD_PARTICIPANT',
  EDIT_PARTICIPANT = 'EDIT_PARTICIPANT',
  COUNTER = 'COUNTER',
  FAQ = 'FAQ',
  TEST_QUESTUIONS = 'TEST_QUESTUIONS',
  PARTNERS = 'PARTNERS',
  ADD_PARTNER = 'ADD_PARTNER',
  EDIT_PARTNER = 'EDIT_PARTNER',
  EDIT_PARTNER_ROUTE = 'EDIT_PARTNER_ROUTE',
  SUPPORTERS = 'SUPPORTERS',
  ADD_SUPPORTER = 'ADD_SUPPORTER',
  EDIT_SUPPORTER = 'EDIT_SUPPORTER',
  EDIT_SUPPORTER_ROUTE = 'EDIT_SUPPORTER_ROUTE',
  DICTATION_QUESTIONS = 'DICTATION_QUESTIONS',
  WATCH_DICTATION_QUESTIONS = 'WATCH_DICTATION_QUESTIONS',
  WATCH_DICTATION_QUESTIONS_ROUTE = 'WATCH_DICTATION_QUESTIONS_ROUTE',
}

export const paths = {
  [AdminsPage.NEWS]: '/admin/news',
  [AdminsPage.NEWS_CREATE]: '/admin/news/create',
  [AdminsPage.NEWS_EDIT]: '/admin/news/edit',
  [AdminsPage.NEWS_EDIT_ROUTE]: '/admin/news/edit/:id',
  [AdminsPage.MAIN]: '/admin/',
  [AdminsPage.MENU]: '/admin/menu',
  [AdminsPage.MENU_ROUTE]: '/admin/menu/:id',
  [AdminsPage.STATISTICS]: '/admin/statistics',
  [AdminsPage.PARTICIPANTS]: '/admin/participants',
  [AdminsPage.ADD_PARTICIPANT]: '/admin/participants/create',
  [AdminsPage.EDIT_PARTICIPANT]: '/admin/participants/edit',
  [AdminsPage.COUNTER]: '/admin/counter',
  [AdminsPage.FAQ]: '/admin/faq',
  [AdminsPage.TEST_QUESTUIONS]: '/admin/test-questions',
  [AdminsPage.PARTNERS]: '/admin/partners',
  [AdminsPage.ADD_PARTNER]: '/admin/partners/create',
  [AdminsPage.EDIT_PARTNER]: '/admin/partners/edit',
  [AdminsPage.EDIT_PARTNER_ROUTE]: '/admin/partners/edit/:id',
  [AdminsPage.SUPPORTERS]: '/admin/supporters',
  [AdminsPage.ADD_SUPPORTER]: '/admin/supporters/create',
  [AdminsPage.EDIT_SUPPORTER]: '/admin/supporters/edit',
  [AdminsPage.EDIT_SUPPORTER_ROUTE]: '/admin/supporters/edit/:id',
  [AdminsPage.DICTATION_QUESTIONS]: '/admin/dictation-questions',
  [AdminsPage.WATCH_DICTATION_QUESTIONS]: '/admin/dictation-questions/watch',
  [AdminsPage.WATCH_DICTATION_QUESTIONS_ROUTE]: '/admin/dictation-questions/watch/:id',
}
